## Numpy Array

In [1]:
import numpy as np

### Convert List into numpy array

In [2]:
mylist = [1,2,3]

In [3]:
numpy_array = np.array(mylist)

### Convert Matrix into numpy array

In [4]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
matrix_numpy = np.array(myMatrix)
print(matrix_numpy)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Create numpy array by arange

In [6]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Create 2 rows 5 columns

In [9]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [14]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(1)

array([0.11788785])

In [18]:
np.random.rand(2,3)

array([[0.21601058, 0.34701092, 0.25051525],
       [0.2379662 , 0.60805636, 0.9843368 ]])

### Return a sample (or samples) from the "standard normal" distribution. (randn)
with mean = 0 and variance = 1

### Parameters
----------
- low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
- high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
- size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
- dtype : dtype, optional
    Desired dtype of the result. Byteorder must be native.
    The default value is int.

In [19]:
np.random.randn(2,3)

array([[ 0.88268303, -0.8451509 ,  0.71840375],
       [-0.62846845,  0.90514915, -0.86431921]])

In [20]:
np.random.randn(23)

array([-0.42182976, -0.75397407,  1.58377635, -0.16449303,  0.20168508,
       -2.23216754,  0.37163253,  1.18656265,  0.33267234,  0.45003688,
       -0.32846191, -1.5917027 , -0.53530063, -0.47075284, -1.4574158 ,
        0.16617431, -0.18322476, -0.95241428,  0.22921747,  0.54843759,
        1.07959274,  0.35569373, -0.38931958])

In [26]:
np.random.randint(1,10)

8

In [28]:
np.random.randint(1,10, 5)

array([6, 3, 3, 4, 3])

In [30]:
np.random.seed(21)
np.random.rand(4)

array([0.04872488, 0.28910966, 0.72096635, 0.02161625])

### Same seed and rand return same result

In [31]:
np.random.seed(21)
np.random.rand(4)

array([0.04872488, 0.28910966, 0.72096635, 0.02161625])

In [33]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ran_arr = np.random.randint(0,101,25)
ran_arr

array([59, 20, 76, 56, 41,  5, 18, 70, 50, 56, 98, 48, 53,  5, 80, 35, 91,
       33, 12, 82, 15,  6, 84, 90, 28])

In [45]:
print(ran_arr.max())
print(ran_arr.min())
print(ran_arr.argmax()) # index of maximum value in the list
print(ran_arr.argmin())
print(ran_arr.dtype)

98
5
10
5
int32


In [46]:
ran_arr.shape

(25,)

In [47]:
ran_arr = ran_arr.reshape(5,5)
ran_arr

array([[59, 20, 76, 56, 41],
       [ 5, 18, 70, 50, 56],
       [98, 48, 53,  5, 80],
       [35, 91, 33, 12, 82],
       [15,  6, 84, 90, 28]])

In [48]:
ran_arr.shape

(5, 5)

In [49]:
ran_arr = ran_arr.reshape(25,1)
ran_arr

array([[59],
       [20],
       [76],
       [56],
       [41],
       [ 5],
       [18],
       [70],
       [50],
       [56],
       [98],
       [48],
       [53],
       [ 5],
       [80],
       [35],
       [91],
       [33],
       [12],
       [82],
       [15],
       [ 6],
       [84],
       [90],
       [28]])

In [50]:
ran_arr = ran_arr.reshape(1,25)
ran_arr

array([[59, 20, 76, 56, 41,  5, 18, 70, 50, 56, 98, 48, 53,  5, 80, 35,
        91, 33, 12, 82, 15,  6, 84, 90, 28]])