## Numpy Array

In [1]:
import numpy as np

### Convert List into numpy array

In [2]:
mylist = [1,2,3]

In [3]:
numpy_array = np.array(mylist)

### Convert Matrix into numpy array

In [4]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
matrix_numpy = np.array(myMatrix)
print(matrix_numpy)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Create numpy array by arange

In [7]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [8]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Create 2 rows 5 columns

In [11]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [16]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand